export const products = [
	{
		id: 1,
		name: 'Beloved',
		img: '/images/sample-product-1.jpg',
		price: 5500,
		size: '89x89cm',
		material: 'wolen',
	},
	{
		id: 2,
		name: 'Sweet Flower',
		img: '/images/sample-product-2.jpg',
		price: 7500,
		size: '148x148cm',
		material: 'wolen',
	},
	{
		id: 3,
		name: 'Eastern Tale',
		img: '/images/sample-product-3.jpg',
		price: 6500,
		size: '125x125cm',
		material: 'wolen',
	},
	{
		id: 4,
		name: 'Beloved',
		img: '/images/woolen-89-1.jpg',
		price: 5500,
		size: '89x89cm',
		material: 'wolen',
	},
	{
		id: 5,
		name: 'Sweet Flower',
		img: '/images/woolen-89-2.jpg',
		price: 5500,
		size: '89x89cm',
		material: 'wolen',
	},
	{
		id: 6,
		name: 'Eastern Tale',
		img: '/images/woolen-89-3.jpg',
		price: 5500,
		size: '89x89cm',
		material: 'wolen',
	},
	{
		id: 7,
		name: 'Beloved',
		img: '/images/woolen-125-1.jpg',
		price: 6500,
		size: '125x125cm',
		material: 'wolen',
	},
	{
		id: 8,
		name: 'Sweet Flower',
		img: '/images/woolen-125-2.jpg',
		price: 6500,
		size: '125x125cm',
		material: 'wolen',
	},
	{
		id: 9,
		name: 'Eastern Tale',
		img: '/images/woolen-125-3.jpg',
		price: 6500,
		size: '125x125cm',
		material: 'wolen',
	},
	{
		id: 10,
		name: 'Beloved',
		img: '/images/woolen-148-1.jpg',
		price: 7500,
		size: '148x148cm',
		material: 'wolen',
	},
	{
		id: 11,
		name: 'Sweet Flower',
		img: '/images/woolen-148-2.jpg',
		price: 7500,
		size: '148x148cm',
		material: 'wolen',
	},
	{
		id: 12,
		name: 'Eastern Tale',
		img: '/images/woolen-148-3.jpg',
		price: 7500,
		size: '148x148cm',
		material: 'wolen',
	},
]

export const instagramImg = [
	{
		id: 1,
		img: '/images/insta-1.jpg',
	},
	{
		id: 2,
		img: '/images/insta-2.jpg',
	},
	{
		id: 3,
		img: '/images/insta-3.jpg',
	},
	{
		id: 4,
		img: '/images/insta-4.jpg',
	},
	{
		id: 5,
		img: '/images/insta-5.jpg',
	},
	{
		id: 6,
		img: '/images/insta-6.jpg',
	},
	{
		id: 7,
		img: '/images/insta-7.jpg',
	},
	{
		id: 8,
		img: '/images/insta-8.jpg',
	},
]
