import Head from 'next/head'
import Company from '../components/homepage/Company'
import Hero from '../components/homepage/Hero'
import Instagram from '../components/homepage/Instagram'
import FeaturedProducts from '../components/homepage/FeaturedProducts'
import Transaction from '../components/homepage/Transaction'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Hero />
			<FeaturedProducts />
			<Company />
			<Instagram />
			<Transaction />
		</div>
	)
}
