import Head from 'next/head'
import Hero from '../components/homepage/Hero'
import ProductsSample from '../components/homepage/ProductsSample'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Hero />
			<ProductsSample />
		</div>
	)
}
